# Generated by Django 4.2.5 on 2023-09-24 21:04

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='images',
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
    ]
