# Generated by Django 4.2.5 on 2023-09-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_slug_alter_job_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
