# Generated by Django 4.2.5 on 2023-09-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_apply_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='published_at',
            new_name='created_at',
        ),
    ]
