# Generated by Django 4.2.5 on 2023-09-25 16:20

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='images',
            field=models.ImageField(height_field='200', upload_to=job.models.image_upload, width_field='400'),
        ),
    ]
